trigger:
- main

variables:
  acrName: 'poc34acr123'
  acrLoginServer: 'poc34acr123.azurecr.io'
  imageName: 'poc34-webapp'
  tag: '$(Build.BuildId)'

  containerAppName: 'poc34-app'
  resourceGroup: 'poc34-rg'

stages:
- stage: BuildAndPush
  displayName: Build & Push Docker Image to ACR
  jobs:
  - job: BuildPush
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push to ACR
      inputs:
        command: buildAndPush
        containerRegistry: 'ACR-SERVICE-CONNECTION'
        repository: '$(imageName)'
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy to Azure Container App
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureContainerApps@1
      displayName: Deploy image to Container App
      inputs:
        azureSubscription: 'AZURE-RM-SERVICE-CONNECTION'
        acrName: '$(acrName)'
        resourceGroup: '$(resourceGroup)'
        containerAppName: '$(containerAppName)'
        imageToDeploy: '$(acrLoginServer)/$(imageName):$(tag)'
        targetPort: '8080'
